# Generated by Django 5.1.5 on 2025-05-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accountbalance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
