# Generated by Django 5.1.5 on 2025-05-15 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_accountbalance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountbalance', to=settings.AUTH_USER_MODEL),
        ),
    ]
