# Generated by Django 5.0.6 on 2025-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_accountbalance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default='1234', max_length=10),
        ),
    ]
