# Generated by Django 5.0.6 on 2025-08-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='add_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
