# Generated by Django 5.0.6 on 2025-08-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_accountbalance_add_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.TextField(help_text='Enter with 01234567890 ', max_length=11),
        ),
    ]
