# Generated by Django 5.1.5 on 2025-04-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
