# Generated by Django 5.1.5 on 2025-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_pet_options_alter_pet_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.BooleanField(default=False),
        ),
    ]
