# Generated by Django 5.1.5 on 2025-05-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_petimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
    ]
