# Generated by Django 5.1.5 on 2025-05-16 09:05

import cloudinary.models
import pet.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_review_unique_pet_user_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[pet.validators.validate_file_size], verbose_name='image'),
        ),
    ]
