# Generated by Django 5.1.5 on 2025-05-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_alter_petimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
