# Generated by Django 5.0.6 on 2025-08-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_rename_description_review_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='stock',
        ),
    ]
